stages:
  - linting
  - test
  - coverage
  - pages

variables:
  MACSY_VERSION: ${CI_COMMIT_REF_NAME}

ruff:
  stage: linting
  image: python:3.13-slim-bookworm
  script:
    - python3 -m pip install .[dev]
    - ruff check --output-format=gitlab integron_finder/ tests/

testing:
  stage: test
  image: python:3.13-slim-bookworm
  script:
    - apt-get update -y
    - apt-get install -y --no-install-recommends infernal prodigal hmmer
    - python3 -m pip install .[dev]
    - python3 -m unittest discover -vv
  except:
    - /^feat.*$/
    - /^fix.*$/

coverage:
  stage: coverage
  image: python:3.13-slim-bookworm
  script:
    - apt-get update -y
    - apt-get install -y --no-install-recommends infernal prodigal hmmer
    - python3 -m pip install .[dev]
    - coverage run
    - coverage html
    - coverage report

  artifacts:
    paths:
      - coverage_html/
  except:
    - /^feat.*$/
    - /^fix.*$/

pages:
  stage: pages
  image: python:3.13-slim-bookworm
  dependencies:
    - coverage
  script:
    - apt-get update -y
    - apt-get install -y --no-install-recommends make
    - python3 -m pip install .[dev]
    - cd ${CI_PROJECT_DIR}/doc/
    - make html
    - cd ${CI_PROJECT_DIR}
    - mv ${CI_PROJECT_DIR}/doc/build/html/ public
    - mv coverage_html public/coverage
  artifacts:
    paths:
      - public
  only:
    - dev
