language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
# Apply only on main branches
branches:
  except:
       - /^feat.*$/
       - /^issue.*$/

# command to install dependencies
before_install:
  - sudo apt-get update
  - sudo apt-get -y install python3-pip python3-setuptools python3-coverage python3-numpy python3-matplotlib python3-pandas python3-biopython

  - PV="2.6.3"
  - wget https://github.com/hyattpd/Prodigal/archive/v${PV}.tar.gz
  - tar -xf v${PV}.tar.gz
  - cd Prodigal-${PV} && make && sudo make install
  - cd -

  - PV="1.1.4"
  - wget http://eddylab.org/infernal/infernal-${PV}.tar.gz
  - tar -xf infernal-${PV}.tar.gz
  - cd infernal-${PV} && ./configure && make && sudo make install
  - cd -

  - PV="3.3.2"
  - wget http://eddylab.org/software/hmmer/hmmer-${PV}.tar.gz
  - tar -xf hmmer-${PV}.tar.gz
  - cd hmmer-${PV} && ./configure && make && sudo make install
  - cd -

# command to install integron_finder
install:
  - pip3 install .

# test integron_finder
script:
  - coverage run --source integron_finder tests/run_tests.py -vv
  - coverage report

after_success:
  - coveralls

